

DECLARE
@Record_Count INT = 1000,
@Max_LoopCount INT = 0,  /* prevent infinite loop */

@ITEM_ID BIGINT,
@REPOSITORY_ID BIGINT;

DECLARE @SQL NVARCHAR(MAX) = '';

/*** Start Lines ***/
PRINT  '';
PRINT 'DECLARE @database_id INT;'
PRINT 'SELECT @database_id = database_id FROM sys.databases where name = DB_NAME();';
PRINT 'DBCC FLUSHPROCINDB(@database_id);';
PRINT 'DBCC FREEPROCCACHE;';

PRINT 'SET NOCOUNT ON;';
PRINT 'DECLARE @StartTime DATETIME = GETDATE()';
PRINT ',@ITEM_ID BIGINT';
PRINT ',@REPOSITORY_ID BIGINT';
PRINT ';';
PRINT '';

PRINT 'SET STATISTICS IO ON;';
PRINT 'SET STATISTICS TIME ON;';

PRINT '';

SELECT @SQL = @SQL + 'DECLARE @' + COLUMN_NAME + ' ' +
               CASE 
                   WHEN DATA_TYPE = 'varchar' OR DATA_TYPE = 'nvarchar' THEN DATA_TYPE + '(' + 
                        CASE WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN 'MAX'
                             ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) 
                        END + ')'
                   WHEN DATA_TYPE = 'decimal' OR DATA_TYPE = 'numeric' THEN DATA_TYPE + '(' + CAST(NUMERIC_PRECISION AS VARCHAR) + ',' + CAST(NUMERIC_SCALE AS VARCHAR) + ')'
                   ELSE DATA_TYPE 
               END + ';' + CHAR(13) + CHAR(10)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'B_MASTER_REPOSITORY_ITEM' AND COLUMN_NAME NOT IN ('ITEM_ID', 'REPOSITORY_ID');

PRINT @SQL;

PRINT '';

/*** End Start Lines ***/


DECLARE @REPOSITORY_ID_Str VARCHAR(20) = ''
,@CurrentCount INT = 0
;
DECLARE @Start_ITEM_ID BIGINT
SELECT @Max_LoopCount = MAX(ITEM_ID) FROM [dbo].[B_MASTER_REPOSITORY_ITEM];
SET @Start_ITEM_ID = FLOOR(@Max_LoopCount/2)

SELECT @Start_ITEM_ID = MIN(ITEM_ID) FROM [dbo].[B_MASTER_REPOSITORY_ITEM] WHERE [ITEM_ID] >= @Start_ITEM_ID;

WHILE @CurrentCount < @Record_Count AND @Start_ITEM_ID < @Max_LoopCount
BEGIN
	
	SELECT @REPOSITORY_ID = REPOSITORY_ID
	,@ITEM_ID = ITEM_ID
	FROM [dbo].[B_MASTER_REPOSITORY_ITEM] WHERE [ITEM_ID] = @Start_ITEM_ID;

	IF @ITEM_ID IS NOT NULL
	BEGIN
		IF @REPOSITORY_ID IS NULL
			SET @REPOSITORY_ID_Str = 'NULL';
		ELSE
			SET @REPOSITORY_ID_Str = CAST(@REPOSITORY_ID AS VARCHAR(20));
		PRINT '';
		PRINT ' SET @ITEM_ID = ' + CAST(@ITEM_ID AS VARCHAR(20)) + ';';
		PRINT ' SET @REPOSITORY_ID = ' + @REPOSITORY_ID_Str + ';';
		PRINT '';
		PRINT ' SELECT ';
		SET @SQL = N'';
		SELECT @SQL = @SQL + ' @' + COLUMN_NAME + ' = ' + COLUMN_NAME + ',' + CHAR(13) + CHAR(10)
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'B_MASTER_REPOSITORY_ITEM' AND COLUMN_NAME NOT IN ('ITEM_ID', 'REPOSITORY_ID');

		SET @SQL = SUBSTRING(@SQL, 0, LEN(@SQL) - 2);

		PRINT @SQL;

		IF @REPOSITORY_ID IS NULL
			PRINT ' FROM [dbo].[B_MASTER_REPOSITORY_ITEM] WHERE [ITEM_ID] = @ITEM_ID AND [REPOSITORY_ID] IS NULL;';
		ELSE
			PRINT ' FROM [dbo].[B_MASTER_REPOSITORY_ITEM] WHERE [ITEM_ID] = @ITEM_ID AND [REPOSITORY_ID] = @REPOSITORY_ID;';

		SET @CurrentCount = @CurrentCount + 1;
	END; /* IF @ITEM_ID IS NOT NULL */

	SET @Start_ITEM_ID = @Start_ITEM_ID + 1;
END;


/*** Finish Lines ***/
PRINT 'SET STATISTICS IO OFF;';
PRINT 'SET STATISTICS TIME OFF;';
PRINT 'PRINT ''Elasped Time(seconds):'' + CAST( (DATEDIFF(second, @StartTime, GETDATE())) AS VARCHAR(20));';
--PRINT 'PRINT DATEDIFF(second, @StartTime, GETDATE());';
PRINT 'SET NOCOUNT OFF;';

