USE [master]
GO


CREATE DATABASE [DataUsage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClientDataUsage', FILENAME = N'D:\rdsdbdata\DATA\DataUsage.mdf' , SIZE = 8192KB , MAXSIZE = 100GB, FILEGROWTH = 65536KB ), 
 FILEGROUP [UserData] 
( NAME = N'UserData', FILENAME = N'D:\rdsdbdata\DATA\UserData.ndf' , SIZE = 1777664KB , MAXSIZE = 100GB, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClientDataUsage_log', FILENAME = N'D:\rdsdbdata\DATA\DataUsage_log.ldf' , SIZE = 5644288KB , MAXSIZE = 200GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

