CREATE OR REPLACE FUNCTION 
FUNC_GET_CONTROLSIZE(
  Owner VARCHAR2,
  strSearch VARCHAR2,
  strExcludedOne VARCHAR2,
  strExcludedTwo VARCHAR2
) RETURN NUMBER
AS
BEGIN

RETURN NULL;

END FUNC_GET_CONTROLSIZE;