
/* Create FileGroup and File for data */

ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup1];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile1],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile1.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup1];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup2];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile2],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile2.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup2];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup3];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile3],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile3.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup3];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup4];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile4],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile4.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup4];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup5];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile5],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile5.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup5];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup6];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile6],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile6.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup6];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup7];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile7],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile7.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup7];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup8];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile8],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile8.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup8];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup9];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile9],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile9.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup9];
ALTER DATABASE [epim] ADD FILEGROUP [mFileGroup10];
ALTER DATABASE [epim] ADD FILE (NAME = [mFile10],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mFile10.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) TO FILEGROUP [mFileGroup10];

/* Create FileGroup and File for index */


ALTER DATABASE [epim] ADD FILEGROUP [mIndexFileGroup];
ALTER DATABASE [epim] ADD FILE (NAME = [mIndexFile],
     FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EPIM_Data\mIndexFile.ndf',
     SIZE = 100MB, MAXSIZE = UNLIMITED,FILEGROWTH = 100MB ) TO FILEGROUP [mIndexFileGroup];

/* Create Parition Function and Partition Schema */

USE [epim]
GO

CREATE FUNCTION [dbo].[mHashPartition] (@ID BIGINT)
 RETURNS TINYINT
 WITH SCHEMABINDING
 AS
 BEGIN
       RETURN @ID % 10;
 END;
GO

CREATE PARTITION FUNCTION [mHashPartitionFunction](TINYINT)
  AS RANGE LEFT FOR VALUES (0,1,2,3,4,5,6,7,8);
GO

CREATE PARTITION SCHEME [mPartitionScheme]
 AS PARTITION [mHashPartitionFunction]
 TO ([mFileGroup1],[mFileGroup2],[mFileGroup3],[mFileGroup4],[mFileGroup5],[mFileGroup6],[mFileGroup7],[mFileGroup8],[mFileGroup9],[mFileGroup10]);
GO

/* Re-create Primary Key with Partition Schema binding */

ALTER TABLE [dbo].[B_MASTER_REPOSITORY_ITEM] ADD [PartitionKey] AS [dbo].[mHashPartition]([ITEM_ID]) PERSISTED NOT NULL;
GO



ALTER TABLE [dbo].[B_MASTER_REPOSITORY_ITEM] DROP CONSTRAINT [pk__b_master_repo_item];
GO

ALTER TABLE [dbo].[B_MASTER_REPOSITORY_ITEM] ADD  CONSTRAINT [pk__b_master_repo_item] PRIMARY KEY CLUSTERED ([ITEM_ID],[PartitionKey]) ON [mPartitionScheme]([PartitionKey]);
GO

/* Re-Create non-clustered Indexes */

CREATE NONCLUSTERED INDEX [B_MASTER_REP_ITEM_IE1] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( REPOSITORY_ID ASC, ITEM_ID ASC, HAS_ERROR_IND ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO

CREATE NONCLUSTERED INDEX [B_MASTER_REP_ITEM_IE2] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( REPOSITORY_ID ASC, PLT_ITEM_ID ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO

CREATE NONCLUSTERED INDEX [B_MASTER_REP_ITEM_IE3] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( REPOSITORY_ID ASC, PK_COL_1 ASC, PK_COL_2 ASC, PK_COL_3 ASC, PK_COL_4 ASC, PK_COL_5 ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO

CREATE NONCLUSTERED INDEX [B_MASTER_REP_ITEM_IE4] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( REPOSITORY_ID ASC, RECORD_STATE ASC, PRODUCTION_STATE ASC, WORKFLOW_STATE ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO

CREATE NONCLUSTERED INDEX [B_MASTER_REP_ITEM_IE5] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( REPOSITORY_ID ASC, ATTR_LAST_UPDATE_DATETIME ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO

CREATE NONCLUSTERED INDEX [B_MASTER_REP_ITEM_IE7] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( REPOSITORY_ID ASC, ITEM_ID ASC, HAS_ERROR_IND ASC, RECORD_STATE ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO

CREATE NONCLUSTERED INDEX [B_MASTER_REP_ITEM_STAGING_ITEM_ID] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( STAGING_ITEM_ID ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO

CREATE NONCLUSTERED INDEX [B_MASTER_REPOSITORY_ITEM_IE6] ON [dbo].[B_MASTER_REPOSITORY_ITEM] ( REPOSITORY_ID ASC, STAGING_ITEM_ID ASC ) INCLUDE ( [PartitionKey] )  WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DROP_EXISTING = ON ) ON [mIndexFileGroup];
GO


