
DECLARE @maxval BIGINT, @minval BIGINT, @RND_ITEM_ID BIGINT, @COUNT BIGINT = 1

SELECT @maxval = MAX(ITEM_ID), @minval = MIN(ITEM_ID) FROM [dbo].[B_MASTER_REPOSITORY_ITEM_JSON]


WHILE @COUNT < 10
BEGIN

SET @RND_ITEM_ID = CAST(((@maxval + 1) - @minval) *
    RAND(CHECKSUM(NEWID())) + @minval AS BIGINT);

INSERT INTO [dbo].[B_MASTER_REPOSITORY_ITEM]
(
	[REPOSITORY_ID],
	[HAS_ERROR_IND],
	[SYNC_ACTION],
	[SYNC_ACTION_DELETE],
	[IS_DUPLICATE],
	[RECORD_STATE],
	[PRODUCTION_STATE],
	[WORKFLOW_STATE],
	[MESSAGE_ID],
	[TRANSACTION_ID],
	[ATTR_DATA],
    [STATE_UPDATE_TIME],
	[STATE_UPDATE_MSG],
	[RECLOCK],
	[PK_COL_1] ,
	[PK_COL_2],
	[PK_COL_3],
	[PK_COL_4] ,
	[PK_COL_5],
	[CREATION_DATETIME],
	[CREATED_BY] ,
	[LAST_UPDATE_DATETIME],
	[LAST_UPDATE_BY],
	[REPOSITORY_TYPE],
	[MODIFY_ACTION],
	[ATTR_LAST_UPDATE_DATETIME],
	[ATTR_LAST_UPDATE_BY],
	[EXTERNAL_SESSION_INFO],
	[PLT_ITEM_ID],
	[STAGING_ITEM_ID],
	[GLOBAL_IND],
	[VALIDATION_LEVEL_IND],
	[OVERALL_ERROR_IND],
	[HAS_ERROR_IND_1],
	[HAS_ERROR_IND_2],
	[HAS_ERROR_IND_3],
	[HAS_ERROR_IND_4],
	[HAS_ERROR_IND_5] ,
	[SECURITY_CONTEXT_VALUE],
	[MERGED_INTO_ITEM_ID]
)
SELECT 
TOP 1
	[REPOSITORY_ID],
	[HAS_ERROR_IND],
	[SYNC_ACTION],
	[SYNC_ACTION_DELETE],
	[IS_DUPLICATE],
	[RECORD_STATE],
	[PRODUCTION_STATE],
	[WORKFLOW_STATE],
	[MESSAGE_ID],
	[TRANSACTION_ID],
[ATTR_DATA],

[STATE_UPDATE_TIME],
	[STATE_UPDATE_MSG],
	[RECLOCK],
	[PK_COL_1] ,
	[PK_COL_2],
	[PK_COL_3],
	[PK_COL_4] ,
	[PK_COL_5],
	[CREATION_DATETIME],
	[CREATED_BY] ,
	[LAST_UPDATE_DATETIME],
	[LAST_UPDATE_BY],
	[REPOSITORY_TYPE],
	[MODIFY_ACTION],
	[ATTR_LAST_UPDATE_DATETIME],
	[ATTR_LAST_UPDATE_BY],
	[EXTERNAL_SESSION_INFO],
	[PLT_ITEM_ID],
	[STAGING_ITEM_ID],
	[GLOBAL_IND],
	[VALIDATION_LEVEL_IND],
	[OVERALL_ERROR_IND],
	[HAS_ERROR_IND_1],
	[HAS_ERROR_IND_2],
	[HAS_ERROR_IND_3],
	[HAS_ERROR_IND_4],
	[HAS_ERROR_IND_5] ,
	[SECURITY_CONTEXT_VALUE],  
	[MERGED_INTO_ITEM_ID]
FROM [dbo].[B_MASTER_REPOSITORY_ITEM]
WHERE [ITEM_ID] >= @RND_ITEM_ID

	SET @COUNT = @COUNT + 1
END
GO

