
/*   

-- Since the [key] in JSON is different on each row, using view won't work
-- Drop VIEW If Exists [dbo].[B_MASTER_REPOSITORY_ITEM_JSON_VIEW];

-- about 10 times more rows vs the underline table [B_MASTER_REPOSITORY_ITEM]
select count(*) from [B_MASTER_REPOSITORY_ITEM_JSON_VIEW]

*/

CREATE OR ALTER VIEW [dbo].[B_MASTER_REPOSITORY_ITEM_JSON_VIEW]
WITH SCHEMABINDING
AS
SELECT  
[ITEM_ID],
	[REPOSITORY_ID],
	[HAS_ERROR_IND],
	[SYNC_ACTION],
	[SYNC_ACTION_DELETE],
	[IS_DUPLICATE],
	[RECORD_STATE],
	[PRODUCTION_STATE],
	[WORKFLOW_STATE],
	[MESSAGE_ID],
	[TRANSACTION_ID],
--CAST(B.[key] AS NVARCHAR(100)) AS [ATTR_DATA_key],
--CAST(B.[value] AS NVARCHAR(max)) AS [ATTR_DATA_value],

[STATE_UPDATE_TIME],
	[STATE_UPDATE_MSG],
	[RECLOCK],
	[PK_COL_1] ,
	[PK_COL_2],
	[PK_COL_3],
	[PK_COL_4] ,
	[PK_COL_5],
	[CREATION_DATETIME],
	[CREATED_BY] ,
	[LAST_UPDATE_DATETIME],
	[LAST_UPDATE_BY],
	[REPOSITORY_TYPE],
	[MODIFY_ACTION],
	[ATTR_LAST_UPDATE_DATETIME],
	[ATTR_LAST_UPDATE_BY],
	[EXTERNAL_SESSION_INFO],
	[PLT_ITEM_ID],
	[STAGING_ITEM_ID],
	[GLOBAL_IND],
	[VALIDATION_LEVEL_IND],
	[OVERALL_ERROR_IND],
	[HAS_ERROR_IND_1],
	[HAS_ERROR_IND_2],
	[HAS_ERROR_IND_3],
	[HAS_ERROR_IND_4],
	[HAS_ERROR_IND_5] ,
	[SECURITY_CONTEXT_VALUE],  
	[MERGED_INTO_ITEM_ID],
	JSON_VALUE(ATTR_DATA, '$.F_1000000') AS [F_1000000]
FROM [dbo].[B_MASTER_REPOSITORY_ITEM_JSON] A
--CROSS APPLY OPENJSON(A.ATTR_DATA, '$') B
;

CREATE UNIQUE CLUSTERED INDEX [uniq_B_MASTER_REPOSITORY_ITEM_JSON_VIEW]
   ON [dbo].[B_MASTER_REPOSITORY_ITEM_JSON_VIEW] ([ITEM_ID]);
GO
